### ISSUE TITLE
wormhole library crate?

### ISSUE THREAD

**Issue by vu3rdd** [magic-wormhole/magic-wormhole.rs#93] opened 2020-11-18 11:16 UTC
It would be nice if core is a library (or core + some io facilities), so that the library can be built standalone and used in other projects. It would also be nice for cross compiling it into wasm.

**Comment by piegamesde** [comment] 2020-11-18 11:37
Do you want a separate library for each protocol or one for all (optionally with feature flags?). At the moment, the binary is in the same Cargo crate as the library, but it's using Cargo's `[[bin]]` feature and also a feature flag. So it's already possible to use the library without depending on the binary.

But I agree, sooner or later we'll probably want to split the project into a Cargo workspace to have separate lib and bin.

**Comment by vu3rdd** [comment] 2020-11-18 11:47
> Do you want a separate library for each protocol or one for all (optionally with feature flags?). At the moment, the binary is in the same Cargo crate as the library, but it's using Cargo's `[[bin]]` feature and also a feature flag. So it's already possible to use the library without depending on the binary.

I do not know a lot about crates to answer that specific question. I would like to have a `[lib]` attribute in the `Cargo.toml` file where I can specify the `crate-type` (for eg: for android/wasm compilation). Since IO is nicely a separate part from `core`, it probably would make sense to make `core` into a library, perhaps? 

I will read up the Cargo docs.

**Comment by piegamesde** [comment] 2021-01-11 17:48
One thing we need to figure out is the scope of the library: we have many protocols at the moment. Core can easily be used as a library, but the transfer is rather entangled with the binary. I hope it will evolve in such a way that we can have all major parts usable in other crates, but maybe we'll have to keep some parts specific to the binary.

**Comment by piegamesde** [comment] 2021-04-03 11:29
Bump. I'm still unsure what exactly you need and where Wormhole fails to fulfill that need at the moment. If it's mainly about WASM support, see #2 (which needs an update tbh).

**Comment by piegamesde** [comment] 2022-03-23 22:52
Closing as duplicate of #50.

**Closed by piegamesde** 2022-03-23 22:52 UTC
